"""add brand_color to organizations

Revision ID: 29131e9dc678
Revises: 2d1b9e4ca700
Create Date: 2026-06-22 20:51:25.787555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29131e9dc678'
down_revision = '2d1b9e4ca700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('brand_color')

    # ### end Alembic commands ###
