"""add 2fa fields to users

Revision ID: 2d1b9e4ca700
Revises: 78e2f1f46958
Create Date: 2026-06-22 20:49:41.257370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1b9e4ca700'
down_revision = '78e2f1f46958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('totp_backup_codes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_backup_codes')
        batch_op.drop_column('totp_enabled')

    # ### end Alembic commands ###
