"""add job_records table

Revision ID: 4626fbde516c
Revises: cb91a1ee165e
Create Date: 2026-06-22 20:35:48.100311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4626fbde516c'
down_revision = 'cb91a1ee165e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('queue', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rq_job_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rq_job_id')
    )
    with op.batch_alter_table('job_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_records_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_records_name'))

    op.drop_table('job_records')
    # ### end Alembic commands ###
