"""add api_request_logs table

Revision ID: 78e2f1f46958
Revises: 8757bf2ba419
Create Date: 2026-06-22 20:46:43.557611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e2f1f46958'
down_revision = '8757bf2ba419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.create_index('idx_api_request_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_api_request_logs_endpoint', ['endpoint'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_api_request_logs_endpoint')
        batch_op.drop_index('idx_api_request_logs_created_at')

    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
